## Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [33]:
import numpy as np

def infoArray(array):
    if array.ndim > 1:
        raise Exception("ERROR: Array amb més de una dimensió")
    
    total_valors = array.sum()
    valor_min = array.min() 
    valor_max = array.max() 
    suma_acumulada = array.cumsum()
    mitjana = array.mean()
    mediana = np.median(array)
    coeficient_correlacio = np.corrcoef(array)
    desviacio_tipica = np.std(array)
    
    print(
    str(array) + "\n"
    "Total valors: " + str(total_valors) + "\n"
    "Valor mínim: " + str(valor_min) + "\n"
    "Valor màxim: " + str(valor_max) + "\n"
    "Suma acumulada: " + str(suma_acumulada) + "\n"
    "Mitjana: " + str(mitjana) + "\n"
    "Mediana: " + str(mediana) + "\n"
    "Coeficient de correlació: " + str(coeficient_correlacio) + "\n"
    "Desviació típica: " + str(desviacio_tipica) + "\n"
    )

    return total_valors, valor_min, valor_max, suma_acumulada, mitjana, mediana, coeficient_correlacio, desviacio_tipica

array = np.random.randint(1, 9, 3)
infoArray(array)

array = np.arange(12).reshape((3, 4))
infoArray(array)

[7 1 1]
Total valors: 9
Valor mínim: 1
Valor màxim: 7
Suma acumulada: [7 8 9]
Mitjana: 3.0
Mediana: 1.0
Coeficient de correlació: 1.0
Desviació típica: 2.8284271247461903



Exception: ERROR: Array amb més de una dimensió

## Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [55]:
def quadrat(N):
    quadrat = np.random.randint(100, size=(N, N))
    return quadrat

print(quadrat(5))

[[35 62 35  1 79]
 [25 93 82 57 54]
 [11 42 92 25 11]
 [87 53 36  5 73]
 [97 27 43 54 48]]


## Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [43]:
def totalsFilaColumna(taula):
    if taula.ndim != 2:
        raise Exception("ERROR: L'array no és una taula")
    
    totals_fila = taula.sum(axis=1)
    totals_col = taula.sum(axis=0)
    
    return totals_fila, totals_col


taula = np.arange(12).reshape((3, 4))
fila, col = totalsFilaColumna(taula)
print(taula)
print(fila)
print(col)

taula = np.arange(27).reshape((3, 3, 3))
fila, col = totalsFilaColumna(taula)
print(taula)
print(fila)
print(col)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]
[12 15 18 21]


Exception: ERROR: L'array no és una taula

## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [54]:
def coefRel(array_x, array_y):
    # coeficient_correlacio = np.corrcoef(array_x, array_y)[0,1]

    mitjana_x = array_x.mean()
    mitjana_y = array_y.mean()
    
    dif_mitjana_x = np.subtract(array_x, mitjana_x)
    dif_mitjana_y = np.subtract(array_y, mitjana_y)
    
    prod_difx_dify = np.multiply(dif_mitjana_x, dif_mitjana_y)
    
    dif_mitjana_x2 = np.square(np.subtract(array_x, mitjana_x))
    dif_mitjana_y2 = np.square(np.subtract(array_y, mitjana_y))
    
    sum_prod_difx_dify = prod_difx_dify.sum()
    sum_dif_mitjana_x2 = dif_mitjana_x2.sum()
    sum_dif_mitjana_y2 = dif_mitjana_y2.sum()
    
    coeficient_correlacio = sum_prod_difx_dify / np.sqrt(np.multiply(sum_dif_mitjana_x2, sum_dif_mitjana_y2))
    
    return coeficient_correlacio

x = np.array([-2, -1, 0, 1, 2])
y = np.array([4, 1, 3, 2, 0])
print(coefRel(x, y))

# Test per comprovar que el resultat de la funció és correcte
print(np.corrcoef(x, y)[0,1])

-0.7
-0.7
